baseURL = 'watchakorn-18k.github.io/around-python-website'
languageCode = 'th'
title = 'รอบเรื่องไพทอน'
theme = "PaperMod"
paginate = 5
defaultContentLanguage = 'th'
enableInlineShortcodes= true
enableRobotsTXT= true
buildDrafts= false
buildFuture= false
buildExpired= false
enableEmoji= true
pygmentsUseClasses= true

[minify]
disableXML= true

[outputs]
home = ['HTML', 'RSS', 'JSON']

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[languages]
    [languages.th]
    title = 'รอบเรื่องไพทอน'


#ปุ่มแชร์โพสต์
[params]
ShowShareButtons = true
ShareButtons = [ "facebook", "twitter","telegram" ]

#แสดงเวลาอ่าน
ShowReadingTime = true

#แสดงเส้นทาง
ShowBreadCrumbs = true

#หน้าแนะนำ
ShowPostNavLinks = true

#คัดลอกโค้ดได้
ShowCodeCopyButtons = true

ShowToc = true
TocOpen = true
env = "production"
description = "ค้นพบทุกสิ่งที่เกี่ยวข้องกับเว็บไซต์ Python อย่างเป็นทางการ เรียนรู้เกี่ยวกับฟีเจอร์ ฟังก์ชันการทำงาน และแหล่งข้อมูล ตลอดจนประวัติและวิวัฒนาการเมื่อเวลาผ่านไป"
author = "watchakorn-18k"
defaultTheme = "auto"
displayFullLangName = true
ShowRssButtonInSectionTermList = true

#ล้มเหลว assets
[params.assets]
disableFingerprinting = true





#เพิ่มไอคอนเว็บ
favicon = "https://cdn.discordapp.com/attachments/1074447855982477353/1084177576144154624/7gZNMX0-_400x400.png"
favicon16x16 = "https://cdn.discordapp.com/attachments/1074447855982477353/1084177576144154624/7gZNMX0-_400x400.png"
favicon32x32 = "https://cdn.discordapp.com/attachments/1074447855982477353/1084177576144154624/7gZNMX0-_400x400.png"
apple_touch_icon = "https://cdn.discordapp.com/attachments/1074447855982477353/1084177576144154624/7gZNMX0-_400x400.png"
safari_pinned_tab = "https://cdn.discordapp.com/attachments/1074447855982477353/1084177576144154624/7gZNMX0-_400x400.png"

#เพิ่มเมนูหน้าแรก
[[menu.main]]
identifier = "หน้าแรก"
name = "หน้าแรก"
url = "/"
weight = 1

#เพิ่มเมนูหมวดหมู่
[[menu.main]]
identifier = "หมวดหมู่"
name = "หมวดหมู่"
url = "/categories/"
weight = 2

#เพิ่มเมนูแท็ก
[[menu.main]]
identifier = "แท็ก"
name = "แท็ก"
url = "/tags/"
weight = 3

#เพิ่มเมนูค้นหา
[[menu.main]]
identifier = "ค้นหา"
name = "ค้นหา"
url = "/search/"
weight = 4

#เพิ่มเมนูเรื่องราว
[[menu.main]]
identifier = "เรื่องราว"
name = "เรื่องราว"
url = "/archives/"
weight = 5






#โปรไฟล์ที่จะใช้งานกับเว็บไซต์
[params.homeInfoParams]
Title = "รอบเรื่องไพธอน"
Content = "ค้นพบทุกสิ่งที่เกี่ยวข้องกับเว็บไซต์ Python อย่างเป็นทางการ เรียนรู้เกี่ยวกับฟีเจอร์ ฟังก์ชันการทำงาน และแหล่งข้อมูล ตลอดจนประวัติและวิวัฒนาการเมื่อเวลาผ่านไป"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/watchakorn-18k"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/watchakorn-buddeewong-75a489229/"


[params.profileMode]
enabled = true
title = "รอบเรื่องไพธอน"
subtitle = "ค้นพบทุกสิ่งที่เกี่ยวข้องกับเว็บไซต์ Python อย่างเป็นทางการ เรียนรู้เกี่ยวกับฟีเจอร์ ฟังก์ชันการทำงาน และแหล่งข้อมูล ตลอดจนประวัติและวิวัฒนาการเมื่อเวลาผ่านไป"
[[params.profileMode.buttons]]
name = "หมวดหมู่"
url = "https://watchakorn-18k.github.io/around-python-website/categories/"

